# Generated by Django 3.0.7 on 2020-06-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200620_1359'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Public', 'Public')], default='t', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='class_name',
            field=models.ForeignKey(default='ALL', on_delete=django.db.models.deletion.CASCADE, to='classroom.Grade'),
        ),
    ]
